backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "src/pages/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "recipe",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - { label: "Body", name: "body", widget: "text" }
      - { label: "Time", name: "time", widget: "text" }
      - { label: "Portions", name: "portions", widget: "markdown" }
      - { label: "Ingredients", name: "ingredients", widget: "list" }
      - { label: "Category", name: "category", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "categories"
    label: "Categories"
    folder: "src/pages/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "category",
        }
      - { label: "Name", name: "name", widget: "string" }
