backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Rezepte"
    folder: "src/pages/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "recipe",
        }
      - { label: "Titee", name: "title", widget: "string" }
      - { label: "Veröffentlichung", name: "date", widget: "datetime" }
      # - { label: "Beschreibung", name: "description", widget: "text" }
      # - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Hauptbild", name: "featuredImage", widget: "image" }
      - { label: "Ingredients", name: "ingredients", widget: "markdown" }
      - { label: "Anweisungen", name: "body", widget: "markdown" }
      - {
          label: "Dauer",
          name: "time",
          widget: "number",
          default: 60,
          valueType: "int",
        }
      - {
          label: "Portionen",
          name: "portions",
          widget: "number",
          default: 4,
          valueType: "int",
          min: 0,
          max: 50,
          step: 1,
        }
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: true
        options:
          - { label: "Vorspeisen", value: "appetizers" }
          - { label: "Hauptgerichte", value: "maindishes" }
          - { label: "Beilagen", value: "sidedishes" }
          - { label: "Kuchen & Kekse", value: "cake / cookies" }
          - { label: "Brots & Brötchen", value: "bread / buns" }
          - { label: "Desserts", value: "desserts" }
          - { label: "Getränke", value: "drinks" }

      - { label: "Tags", name: "tags", widget: "list" }
  - name: "categories"
    label: "Kategorien"
    folder: "src/pages/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "category",
        }
      - { label: "Englischer Bezeichner", name: "name", widget: "string" }
      - { label: "Titel auf MHM", name: "title", widget: "string" }
